info:
  app:
    name: ${spring.application.name}

spring:
  config:
    import: "optional:configtree:/mnt/secrets/"
  application:
    name: nfdiv-cms
  resources:
    static-locations:
  jackson:
    deserialization:
      ACCEPT_SINGLE_VALUE_AS_ARRAY: true
    serialization:
      FAIL_ON_EMPTY_BEANS: false

server:
  port: 4010

idam:
  client:
    redirect_uri: ${IDAM_API_REDIRECT_URL:http://localhost:8080/authenticated}
    id: divorce
    secret: ${nfdiv.idam-secret:dummysecret}
  api:
    url: ${IDAM_API_BASEURL:http://localhost:4503}
    redirect-url: ${IDAM_API_REDIRECT_URL:http://localhost:8080/authenticated}
  caseworker:
    username: ${nfdiv.idam-caseworker-username:dummycaseworker@test.com}
    password: ${nfdiv.idam-caseworker-password:dummy}
  s2s-auth:
    microservice: ${AUTH_PROVIDER_SERVICE_CLIENT_MICROSERVICE:nfdiv_cms}
    totp_secret: ${nfdiv.cms-service-key:dummysecret}
    url: ${AUTH_PROVIDER_SERVICE_CLIENT_BASEURL:http://localhost:4502}
    port: ${AUTH_PROVIDER_SERVICE_CLIENT_PORT:4502}
    health:
      context-path: ${AUTH_PROVIDER_SERVICE_CLIENT_HEALTH_CONTEXT_PATH:/health}

ccd:
  jurisdictionid: DIVORCE
  casetype: NO_FAULT_DIVORCE
  eventid:
    create: create
    createhwf: hwfCreate
    solicitorCreate: solicitorCreate
    create-draft: draftCreate
  bulk:
    casetype: NO_FAULT_DIVORCE_BulkAction
    eventid:
      create: scheduleCreate
  server:
    port: 4452
    health:
      context-path: /status/health

core_case_data:
  api:
    url: ${CASE_DATA_STORE_BASEURL:http://localhost:4452}

http:
  connect:
    timeout: 60000
    request:
      timeout: 60000

health:
  check:
    http:
      connect:
        timeout: 5000
        request:
          timeout: 5000

documentation:
  swagger:
    enabled: true

# GENERAL SPRING BOOT ACTUATOR CONFIG
# Context path for Spring Boot Actuator endpoints
# Allow actuator endpoints to be accessed without requiring authentication
# Enable default health indicators
# Enable disk space health check
management:
  endpoint:
    health:
      show-details: "ALWAYS"
      cache:
        time-to-live: 4000
  endpoints:
    web:
      base-path: /
      exposure:
        include: health, info, prometheus

logging:
  level:
    org.springframework.web: ERROR
    uk.gov.hmcts.reform.divorce.casemaintenanceservice: DEBUG
  pattern:
    console: "%d{yyyy-MMM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{15} - %msg%n"

feign:
  client:
    config:
     core-case-data-api:
        connectTimeout: 10000
        readTimeout: 10000
        loggerLevel: full


azure:
  application-insights:
    instrumentation-key: ${nfdiv.AppInsightsInstrumentationKey:00000000-0000-0000-0000-000000000000}
