java:
    applicationPort: 4010
    aadIdentityName: nfdiv
    ingressHost: "nfdiv-cms-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal"
    environment:
        IDAM_API_BASEURL: "https://idam-api.{{ .Values.global.environment }}.platform.hmcts.net"
        AUTH_PROVIDER_SERVICE_CLIENT_BASEURL: "http://rpe-service-auth-provider-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal"
        IDAM_API_REDIRECT_URL: "https://div-pfe-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal/authenticated"
        CASE_DATA_STORE_BASEURL: "http://ccd-data-store-api-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal"
        AUTH_PROVIDER_SERVICE_CLIENT_TOKENTIMETOLIVEINSECONDS: "900"
        LOG_LEVEL: DEBUG
        MANAGEMENT_ENDPOINT_HEALTH_CACHE_TIMETOLIVE: "30000"
        DOCUMENTATION_SWAGGER_ENABLED: true
    keyVaults:
        nfdiv:
            resourceGroup: nfdiv
            secrets:
                - AppInsightsInstrumentationKey
                - cms-service-key
                - idam-secret
                - idam-caseworker-username
                - idam-caseworker-password
